application:
  port: 8000
database:
  host: "localhost"
  port: 15432
  username: "postgres"
  password: "pa55word"
  database_name: "newsletter"
email_client:
  base_url: "localhost"
  sender_email: "dev@cirovindi.co"
  authorization_token: "BOMB"